---
- name: Deploying config to Fortigate
  fortios_config:
    backup: no
    src: "{{ build_location }}"
    username: admin
    password: 'Labrat@123'
    host: 192.168.1.108
    timeout: 3
  register: fortios

#- name: debug
#  debug:
#    msg: "{{ fortios }}"
