---
- name: Mandatory control compliance check
  parser_metadata:
    version: 1.0
    command: Config Builder for NES007
    network_os: fortios

#- name: pattern match
#  pattern_match:
#    regex: config system global
#    match_all: yes
#    match_greedy: yes
#  register: admin_lockout
#  export: yes

- name: pattern group
  pattern_group:
  - pattern_match:
      regex: "set hostname (.*)"
#      content: "{{ item }}"
      match_all: true
      match_greedy: false
    register: admin_lockout
  register: mapped_commands
  export: true
  export_as: "{{ export_type }}"

- name: generate json data structure  
  json_template:
    template:
      - key: "{{ ansible_host }}"
        object:
          - key: SIA 1.3.5.1.25 - Enforce At Least 30 Minutes Account Re-Activation Delay (Auto Re-Activation Process Only)
            object:
              - key: command 1
#                value: "{{ item.admin_lockout.0 }}"
                value: "{{ mapped_commands.admin_lockout.matches.0 }}"
#                value: "{{ admin_lockout.0.matches }}"
  export: true
  register: control_mapping